### ISSUE TITLE
crash on rest request

### ISSUE THREAD

**Issue by arsen3d** [BlackTurtle123/TurtleNetwork#11]
![screenshot 2018-06-03 13 28 21](https://user-images.githubusercontent.com/298235/40890904-160b87e2-6732-11e8-981c-89d72d1f71a0.png)

**Comment by BlackTurtle123** [comment]
What java versions?
What node version?

**Comment by gord0b** [comment]
Was this issue solved? 
The latest node release is 0.13.6 (https://github.com/BlackTurtle123/TurtleNetwork/tree/v0.13.6). 
If i also review the above no .conf file was specified during the initial server startup, use "java -jar TN-all-0.13.6.jar TN-mainnet.conf" and make sure the .conf file is in the directory and configured correctly.
