### ISSUE TITLE
Is there any source code of this old blockexplorer?

### ISSUE THREAD

**Issue by username1565** [BlackTurtle123/TurtleNetwork#19]
Hello.
Is there any source code of this old blockexplorer? https://explorer.blackturtle.eu/#!/blocks/1

**Comment by BlackTurtle123** [comment]
https://github.com/BlackTurtle123/WavesExplorerLite

**Comment by username1565** [comment]
No, this is not that block-explorer... And... [This is not opening](https://wavesexplorer.com/testnet/) for me:
`Failed to load blockchain info`

**Comment by BlackTurtle123** [comment]
That is that block explorer which we use.

**Comment by username1565** [comment]
@BlackTurtle123, thanks!
I just compared the source code of HTML page index.html .
I see this is that blockexplorer, which you use.
This is old blockexplorer, but in README.md there is the link for NEW blockexplorer, and this not working for me.

I see also, WAVES have the source code of this old block-explorer https://wavesblockexplorer.com/
and this is here too: https://github.com/wavesplatform/WavesExplorerLite/tree/old-explorer
but inside the branch "old-explorer".

Best Regards.
