### ISSUE TITLE
Matcher dex extension

### ISSUE THREAD

**Issue by username1565** [BlackTurtle123/TurtleNetwork#23]
Hello. I see TurtleNetwork have dex extensions here: https://github.com/TurtleNetwork/dex
But, inside `.jar`-file, from latest `Release` [tn-dex-extension-1.2.3.zip](https://github.com/TurtleNetwork/dex/releases/tag/v1.2.3)
I do not see `matcher`-extension, there is just `grpc`-server.

I see only one working matcher, by this url: https://privatematcher.blackturtle.eu
And as I can see here: https://statistics.turtlenetwork.eu/nodes/
no one node have no enabled matcher.

Some nodes in waves-mainnet have enabled matcher, as you can see here: https://dev.pywaves.org/nodes/

So can you fix this, and add matcher? I want to be matcher.
Or TurtleNetwork is not really dex, and `dex`-extensions really not a dex (Decentralized EXchange)??
What if [your url](https://privatematcher.blackturtle.eu) will not working in future, or just will be banned?
All TurtleNetwork will shutdown forever?
Anyway, on real dex, need to be able to raise an althernative matchers, IMHO.

**Comment by BlackTurtle123** [comment]
Having multiple matchers is possible. Please use the debian files.
Also there is a second dex already based on TN.
Polarity.exchange

**Comment by username1565** [comment]
Hello, @BlackTurtle123 ! Thanks for your answer.
I do not understand, what `debian`-files (`.deb`-files), need to use, and how to raise matcher. Do you have any guide to do this?
I see here: https://polarity.exchange/ , inside the wallet, in "User logo -> Settings -> Network",
there is specified a `matcher address`: https://dex.polarity.exchange/matcher
which return, by this url, the public key:
```
"98s7eAwLK56nCRf1vdJhWyyY9hoWviaCvfJAyj5zyJS6"
```

Here: https://wallet.turtlenetwork.eu , inside the wallet, in "User logo -> Settings -> Network",
there is specified a `matcher address`: https://matcher.turtlenetwork.eu/matcher
which return, by this url, the public key:
```
"65MFhgwcGK3bmXzZNgepHF6jUrUmzNZWXZtZBWokvpDZ"
```
which is equal of public key, returned by this url: https://privatematcher.blackturtle.eu/matcher

I do not want to make some another new exchanges, based on TurtleNetwork,
but I just want to be able to raise my own matcher,
if the connect by your hardcoded `matcher-URL`s will be bad,
or in the case, when traffic between clients, and this `URLs`, will be blocked,
or if this matcher `URL`'s will be unavailable in our country.

I see, inside the both exchanges, in "User logo -> Settings -> Network",
there is possible to change matcher URL, and use this exchange as is, with official blockchain,
but just with another, with an althernative matcher.

Also, I see, there is opened a swagger with matcher-rest-API: https://privatematcher.blackturtle.eu/api-docs/index.html
I just want to try to raise my own matcher, on windows, and see this swagger on localhost,
and raise this, by using some `.jar`-files in extensions,
like this is possible with waves, by running the node `.jar`-file, with extensions:
[dex-1.0.2.tgz](https://github.com/wavesplatform/matcher/releases/tag/v1.0.2).
There, inside this `.tgz`-archive, you can see `com.wavesplatform.dex-1.0.2.jar`,
And, if you'lll open this `.jar` with `7zip`, as `7z`-archive,
you can see the some matcher-related files there, in the folder:
`disk:\\blahblah-my-pathway\dex-1.0.2\lib\com.wavesplatform.dex-1.0.2.jar\com\wavesplatform\dex\`.

You say, there is possible to use `.deb`-files, and I see,
the `.jar`-file, like this, with the matcher extensions, is contains inside [`dex_1.0.2_all.deb`](https://github.com/wavesplatform/matcher/releases/tag/v1.0.2), if this `.deb`-file will be opened as `7z`-archive.

But inside [`tn-dex-extension_1.2.3_all.deb`](https://github.com/TurtleNetwork/dex/releases/tag/v1.2.3) I do not see some `.jar`-files with matcher `dex`-extension.

Inside the fat [`tn-dex_1.2.3_all.deb`](https://github.com/TurtleNetwork/dex/releases/tag/v1.2.3),
I see some `tn-dex_1.2.3_all.deb\.\usr\share\tn-dex\lib\com.wavesplatform.dex-1.2.3.jar`
And this seems, like some matcher-methods and functions, there is contains inside.

But this return some throw exceptions, if just copy and paste this .jar-file,
and how to configure this, I do not know. I do not understand this scala-code at all.
Maybe, you are already have some guide, how to set up matcher,
and maybe, you can fix this for Windows, by using `.jar-file` with extensions, and some additional strings in `.conf`-file.

**Comment by BlackTurtle123** [comment]
Each matcher is his own dex.
It can use the same wallet, but orderbooks aren't shared.
Also https://github.com/TurtleNetwork/dex the readme from point 6 contains all info.
Regards

**Comment by username1565** [comment]
@BlackTurtle123, by link, there is no any word, about matcher.
But here, it is: https://github.com/wavesplatform/matcher#-configration-of-matcher-extension
there is described a config, to run grpc-extension, but not a matcher-rest-api ([that swagger, on port 6886](https://privatematcher.blackturtle.eu/))
Full config - here: https://github.com/wavesplatform/matcher/blob/82ce0f08b5e456aebde05770d274677f86b5712b/dex/src/main/container/dex.conf

Yes, i know, that orders are not synchronized decentralized, and matcher, this is a semi-decentralized point of dex,
this matcher is storing this orders, within 29 days max (then auto-cancelleration).
But all another things, a trading history, marketdata, blockchain, etc... there is working really decentralized,
and this is inside official network.
So, I do not think, the another matcher this is a another dex, this is the same dex,
and this can working, on Waves DEX, just by changing a matcher-url, inside the wallet.

Morever, as you can see here: https://dev.pywaves.org/nodes/
some nodes have enabled matcher `yes`,
and this nodes have IP.
This matcher-rest-api, can be opened there by url:
http://IP_NODE:6886/

But here: https://statistics.turtlenetwork.eu/nodes/
no one node have no enabled matcher, because no any guide to raise this, and no any working dex-extensions, to make this working.

So, there is possible, to add a working matcher-extensions, and the guide to configure and raise the matcher-rest-api,
and then, just add a dropdown menu, in the wallet, by using this data (about the nodes with enabled matcher),
and add this to select the available matcher in the mainnet,
and make by this way, the TurtleNetwork DEX - really decentralized!

After all, as I see, on waves.exchange the option to change a macher was been disabled.
This means, this is just an another centralized exchange, with their admins, and moderations,
moreover this is a scam, because they say about buying bitcoins, and leasing a dollars,
but really, they just sell their WBTC for people's BTC and USD-N for people's USD,
then take their money, hold it, and just baning users, then.
And trading by so many liquid assets, just was been banned there.
This is a degenerative evolution of DEX, just because this is not a DEX,
and just an another scam-shit and centralized toilet. IMHO.

**Comment by BlackTurtle123** [comment]
Matcher or DEX is the same, so like i said from point 6 the instructions are written down.
Just a different name by waves used.
You need all points from 6. The dex needs both a stand alone item and a extension on the node. And yes this works through grpc.
